"""empty message

Revision ID: 1363b2663970
Revises: 
Create Date: 2024-03-28 10:06:06.929284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1363b2663970'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('DID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departmentName', sa.String(length=200), nullable=False),
    sa.Column('departmentType', sa.Enum('METALLURGY', 'EQUIPMENT_MANUFACTURING', 'COMPOSITE_MATERIAL', 'NEW_ENERGY', 'AUTOMATION_SYSTEM', 'MAINTENANCE', 'LABORATORY', 'DATA_CENTER', 'OFFICE', name='departmenttype'), nullable=False),
    sa.Column('departmentAddress', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('DID')
    )
    op.create_table('processCapacity',
    sa.Column('PCID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wasteType', sa.Enum('HEAVY_METAL_WASTEWATER', 'EXHAUST_GAS', 'MINERAL_RESIDUE', 'CUTTING_FLUID', 'METAL_CHIPS', 'PLASTIC', 'COMPOSITE_MATERIAL_CUTTING_WASTE', 'WASTE_PAINT', 'DUST', 'CHEMICALS', 'CATALYZER', 'CHEMICAL_PROPELLANTS', 'FUEL_RESIDUES', 'DISCARDED_ELECTRONIC_COMPONENTS', 'HYDRAULIC_OIL', 'LUBRICANT_WASTE', 'HAZARDOUS_CHEMICALS', 'WASTE_EXPERIMENTAL_EQUIPMENT', 'WASTE_PAPER', 'HOUSEHOLD_WASTE', 'WASTE_HEAT', name='wastetype'), nullable=False),
    sa.Column('maxCapacity', sa.Integer(), nullable=False),
    sa.Column('currentCapacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('PCID')
    )
    op.create_table('waste',
    sa.Column('WID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wasteType', sa.Enum('HEAVY_METAL_WASTEWATER', 'EXHAUST_GAS', 'MINERAL_RESIDUE', 'CUTTING_FLUID', 'METAL_CHIPS', 'PLASTIC', 'COMPOSITE_MATERIAL_CUTTING_WASTE', 'WASTE_PAINT', 'DUST', 'CHEMICALS', 'CATALYZER', 'CHEMICAL_PROPELLANTS', 'FUEL_RESIDUES', 'DISCARDED_ELECTRONIC_COMPONENTS', 'HYDRAULIC_OIL', 'LUBRICANT_WASTE', 'HAZARDOUS_CHEMICALS', 'WASTE_EXPERIMENTAL_EQUIPMENT', 'WASTE_PAPER', 'HOUSEHOLD_WASTE', 'WASTE_HEAT', name='wastetype'), nullable=False),
    sa.Column('wasteDepartment', sa.Enum('METALLURGY', 'EQUIPMENT_MANUFACTURING', 'COMPOSITE_MATERIAL', 'NEW_ENERGY', 'AUTOMATION_SYSTEM', 'MAINTENANCE', 'LABORATORY', 'DATA_CENTER', 'OFFICE', name='departmenttype'), nullable=True),
    sa.Column('wasteSource', sa.Enum('INTERNAL', 'EXTERNAL', 'EXTERNALFREE', name='wastesource'), nullable=False),
    sa.PrimaryKeyConstraint('WID')
    )
    op.create_table('wasteStorage',
    sa.Column('WSID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wasteType', sa.Enum('HEAVY_METAL_WASTEWATER', 'EXHAUST_GAS', 'MINERAL_RESIDUE', 'CUTTING_FLUID', 'METAL_CHIPS', 'PLASTIC', 'COMPOSITE_MATERIAL_CUTTING_WASTE', 'WASTE_PAINT', 'DUST', 'CHEMICALS', 'CATALYZER', 'CHEMICAL_PROPELLANTS', 'FUEL_RESIDUES', 'DISCARDED_ELECTRONIC_COMPONENTS', 'HYDRAULIC_OIL', 'LUBRICANT_WASTE', 'HAZARDOUS_CHEMICALS', 'WASTE_EXPERIMENTAL_EQUIPMENT', 'WASTE_PAPER', 'HOUSEHOLD_WASTE', 'WASTE_HEAT', name='wastetype'), nullable=False),
    sa.Column('maxCapacity', sa.Integer(), nullable=False),
    sa.Column('currentCapacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('WSID')
    )
    op.create_table('order',
    sa.Column('OID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('DID', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('orderName', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('attribution', sa.Text(), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('orderStatus', sa.Enum('UNCONFIRMED', 'CONFIRM', 'UNPROCESSED', 'PROCESSING', 'DISCHARGED', name='orderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['DID'], ['department.DID'], ),
    sa.PrimaryKeyConstraint('OID')
    )
    op.create_table('user',
    sa.Column('UID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DEPARTMENT_MANAGER', 'WASTE_MANAGER', 'GOVERNMENT_MANAGER', 'INDIVIDUAL_USER', name='userstatus'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.DID'], ),
    sa.PrimaryKeyConstraint('UID'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('order')
    op.drop_table('wasteStorage')
    op.drop_table('waste')
    op.drop_table('processCapacity')
    op.drop_table('department')
    # ### end Alembic commands ###
